export const CONSTANTS = {
  ROLES: {
    STUDENT: 'student',
    BUSINESS: 'business',
    ADMIN: 'admin'
  },
  NOTIFICATION_TYPES: {
    APPLICATION_RECEIVED: 'APPLICATION_RECEIVED',
    APPLICATION_ACCEPTED: 'APPLICATION_ACCEPTED',
    APPLICATION_REJECTED: 'APPLICATION_REJECTED',
    NEW_MESSAGE: 'NEW_MESSAGE',
    PROJECT_COMPLETED: 'PROJECT_COMPLETED',
    PROFILE_VIEW: 'PROFILE_VIEW'
  },
  APPLICATION_STATUS: {
    PENDING: 'pending',
    SHORTLISTED: 'shortlisted',
    ACCEPTED: 'accepted',
    REJECTED: 'rejected'
  }
};
